config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  post '/send_email', to: 'welcome#send_email', as: 'send_email'
  root 'welcome#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def send_email
    MyMailer.send_email(name: params[:name], phone: params[:phone], email: params[:email], message: params[:message]).deliver
    redirect_to root_url, notice: "Email sent!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MySesApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == 'notice' ? "info" : "danger" %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <i class="fa-fw fa fa-info"></i>
      <strong><Info><%= name %></strong> <%= raw(msg) %>
    </div>
<% end %>

<h1 class="text-center">AWS SES Email Example</h1>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="well well-sm">
        <%= form_tag(send_email_path, method: "post", :class=>"form-horizontal") do %>
            <fieldset>
              <legend class="text-center">Contact us</legend>

              <!-- Name input-->
              <div class="form-group">
                <label class="col-md-3 control-label" for="name">Name</label>
                <div class="col-md-9">
                  <input id="name" name="name" type="text" placeholder="Your name" class="form-control">
                </div>
              </div>

              <!-- Email input-->
              <div class="form-group">
                <label class="col-md-3 control-label" for="email">Your E-mail</label>
                <div class="col-md-9">
                  <input id="email" name="email" type="text" placeholder="Your email" class="form-control">
                </div>
              </div>

              <!-- Message body -->
              <div class="form-group">
                <label class="col-md-3 control-label" for="message">Your message</label>
                <div class="col-md-9">
                  <textarea class="form-control" id="message" name="message" placeholder="Please enter your message here..." rows="5"></textarea>
                </div>
              </div>

              <!-- Form actions -->
              <div class="form-group">
                <div class="col-md-12 text-right">
                  <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                </div>
              </div>
            </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>